const STORAGE_KEY = "SCHOOL_DDAY_TASKS";
const LEGACY_STORAGE_KEY = "school-dday-dashboard.tasks.v1";
const CATEGORIES = ["공문/보고", "품의/정산", "학급/학생", "행사/수업", "연수/기타"];
const PRIORITIES = ["긴급", "보통", "여유"];
const INITIAL_SAMPLE_TASK_IDS = new Set(["T-01", "T-02", "T-03", "T-04", "T-05", "T-06"]);
const GENERAL_WORKFLOW_STEPS = [
  { offset: 30, title: "목표·대상·범위를 정하고 기본 계획 세우기" },
  { offset: 21, title: "담당자 역할과 예산·협조 사항 정리하기" },
  { offset: 14, title: "필요 자료·물품·장소와 안전 사항 준비하기" },
  { offset: 7, title: "관련 구성원에게 안내하고 참여 현황 확인하기" },
  { offset: 3, title: "진행 순서와 비상 대응 방법 점검하기" },
  { offset: 1, title: "최종 체크리스트로 빠진 준비 확인하기" }
];
let memoryTasks = null;

const state = { tasks: [], filter: "all", query: "", loading: true, saving: false, pendingTask: null, workflowDraft: [], workflowSource: "general" };

const elements = {
  userStatusPanel: document.querySelector("#user-status-panel"),
  userStatusText: document.querySelector("#user-status-text"),
  workflowAlertsSection: document.querySelector("#workflow-alerts-section"),
  workflowAlertList: document.querySelector("#workflow-alert-list"),
  workflowAlertCount: document.querySelector("#workflow-alert-count"),
  taskList: document.querySelector("#task-list"),
  loading: document.querySelector("#loading-state"),
  empty: document.querySelector("#empty-state"),
  resultCount: document.querySelector("#result-count"),
  search: document.querySelector("#task-search"),
  filterAllCount: document.querySelector("#filter-all-count"),
  filters: document.querySelector("#filters"),
  modal: document.querySelector("#task-modal"),
  openModal: document.querySelector("#open-modal"),
  closeModal: document.querySelector("#close-modal"),
  cancelModal: document.querySelector("#cancel-modal"),
  form: document.querySelector("#task-form"),
  titleInput: document.querySelector("#task-title"),
  dueDateInput: document.querySelector("#task-due-date"),
  submitTask: document.querySelector("#submit-task"),
  formError: document.querySelector("#form-error"),
  workflowReview: document.querySelector("#workflow-review"),
  workflowReviewLoading: document.querySelector("#workflow-review-loading"),
  workflowReviewContent: document.querySelector("#workflow-review-content"),
  workflowStepList: document.querySelector("#workflow-step-list"),
  workflowSource: document.querySelector("#workflow-source"),
  workflowReviewError: document.querySelector("#workflow-review-error"),
  addWorkflowStep: document.querySelector("#add-workflow-step"),
  backToTask: document.querySelector("#back-to-task"),
  confirmWorkflow: document.querySelector("#confirm-workflow"),
  toast: document.querySelector("#toast"),
  statUrgent: document.querySelector("#stat-urgent"),
  statSoon: document.querySelector("#stat-soon"),
  statProgress: document.querySelector("#stat-progress"),
  statRate: document.querySelector("#stat-rate"),
  statCompleted: document.querySelector("#stat-completed"),
  statProgressBar: document.querySelector("#stat-progress-bar")
};

function isGasEnvironment() {
  return typeof google !== "undefined" && google.script && google.script.run;
}

function startOfToday() {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate());
}

function formatLocalDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function parseLocalDate(value) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value));
  if (!match) return new Date(NaN);
  return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
}

function getDaysUntil(dueDate) {
  return Math.round((parseLocalDate(dueDate) - startOfToday()) / 86400000);
}

function getDday(task) {
  const days = getDaysUntil(task.dueDate);
  if (days < 0) return { label: `D+${Math.abs(days)}`, tone: "overdue", days };
  if (days === 0) return { label: "오늘 마감", tone: "today", days };
  if (days <= 3) return { label: `D-${days}`, tone: "soon", days };
  return { label: `D-${days}`, tone: "normal", days };
}

function normalizeTask(task) {
  return {
    id: String(task.id || ""),
    title: String(task.title || task.taskName || ""),
    dueDate: String(task.dueDate || ""),
    category: CATEGORIES.includes(task.category) ? task.category : CATEGORIES[0],
    priority: PRIORITIES.includes(task.priority) ? task.priority : "보통",
    memo: String(task.memo || ""),
    completed: task.completed === true || task.isCompleted === true || String(task.completed).toLowerCase() === "true" || String(task.isCompleted).toLowerCase() === "true",
    owner: String(task.owner || task.authorEmail || task.email || "담당 교직원"),
    autoGenerated: task.autoGenerated === true || String(task.autoGenerated).toLowerCase() === "true",
    parentTaskId: String(task.parentTaskId || ""),
    workflowTitle: String(task.workflowTitle || ""),
    workflowOffset: Number(task.workflowOffset || 0),
    createdAt: String(task.createdAt || "")
  };
}

function loadLocalTasks() {
  if (Array.isArray(memoryTasks)) return memoryTasks.map(normalizeTask);
  try {
    const current = localStorage.getItem(STORAGE_KEY);
    const legacy = localStorage.getItem(LEGACY_STORAGE_KEY);
    const stored = JSON.parse(current || legacy || "null");
    if (Array.isArray(stored)) {
      const normalized = stored.map(normalizeTask).filter((task) => !INITIAL_SAMPLE_TASK_IDS.has(task.id));
      if (normalized.length !== stored.length || (!current && legacy)) saveLocalTasks(normalized);
      return normalized;
    }
  } catch (error) {
    console.warn("저장된 로컬 데이터를 읽지 못했습니다.", error);
  }
  saveLocalTasks([]);
  return [];
}

function saveLocalTasks(tasks) {
  memoryTasks = tasks.map(normalizeTask);
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(memoryTasks));
  } catch (error) {
    console.warn("LocalStorage를 사용할 수 없어 현재 세션에만 저장합니다.", error);
  }
}

function gasCall(method, ...args) {
  return new Promise((resolve, reject) => {
    const runner = google.script.run
      .withSuccessHandler(resolve)
      .withFailureHandler((error) => reject(new Error(error && error.message ? error.message : String(error))));
    runner[method](...args);
  });
}

const taskService = {
  async getTasks() {
    return isGasEnvironment() ? gasCall("getTasks") : loadLocalTasks();
  },
  async createTask(task) {
    if (isGasEnvironment()) return gasCall("createTask", task);
    const created = normalizeTask({ ...task, id: `local-${Date.now()}-${Math.random().toString(16).slice(2)}`, completed: false, createdAt: new Date().toISOString() });
    saveLocalTasks([...loadLocalTasks(), created]);
    return created;
  },
  async toggleTaskStatus(id, completed) {
    if (isGasEnvironment()) return gasCall("toggleTaskStatus", id, completed);
    const tasks = loadLocalTasks();
    const target = tasks.find((task) => task.id === id);
    if (!target) throw new Error("업무를 찾을 수 없습니다.");
    target.completed = Boolean(completed);
    saveLocalTasks(tasks);
    return target;
  },
  async deleteTask(id) {
    if (isGasEnvironment()) return gasCall("deleteTask", id);
    const tasks = loadLocalTasks();
    if (!tasks.some((task) => task.id === id)) throw new Error("삭제할 업무를 찾을 수 없습니다.");
    saveLocalTasks(tasks.filter((task) => task.id !== id));
    return { id };
  },
  async getCurrentUserEmail() {
    return isGasEnvironment() ? gasCall("getCurrentUserEmail") : "";
  }
};

function dateBefore(value, days) {
  const date = parseLocalDate(value);
  date.setDate(date.getDate() - days);
  return formatLocalDate(date);
}

function normalizeWorkflowSteps(steps) {
  return (Array.isArray(steps) ? steps : [])
    .map((step, index) => ({
      id: String(step.id || `step-${Date.now()}-${index}-${Math.random().toString(16).slice(2)}`),
      title: String(step.title || "").trim().slice(0, 100),
      offset: Math.max(0, Math.min(365, Math.round(Number(step.offset) || 0))),
      description: String(step.description || "").trim().slice(0, 160),
      included: step.included !== false
    }))
    .filter((step) => step.title)
    .sort((a, b) => b.offset - a.offset);
}

function buildGeneralWorkflow(task) {
  const remainingDays = Math.max(0, getDaysUntil(task.dueDate));
  let steps = GENERAL_WORKFLOW_STEPS.filter((step) => step.offset <= remainingDays);
  if (steps.length < 3) {
    const compactOffsets = [...new Set([Math.floor(remainingDays * 0.8), Math.floor(remainingDays * 0.45), Math.min(1, remainingDays)])]
      .filter((offset) => offset >= 0)
      .sort((a, b) => b - a);
    const compactTitles = [
      "목표와 완료 기준을 정하고 실행 계획 세우기",
      "필요한 자료·협조·준비물을 확보하기",
      "결과물을 검토하고 빠진 사항 최종 확인하기"
    ];
    steps = compactOffsets.map((offset, index) => ({ offset, title: compactTitles[index] }));
  }
  return normalizeWorkflowSteps(steps);
}

const workflowService = {
  async suggest(task) {
    if (isGasEnvironment() || location.protocol === "file:") {
      return { source: "general", steps: buildGeneralWorkflow(task) };
    }
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 12000);
    try {
      const response = await fetch("/api/workflow", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(task),
        signal: controller.signal
      });
      if (!response.ok) throw new Error("AI 제안을 불러오지 못했습니다.");
      const result = await response.json();
      const steps = normalizeWorkflowSteps(result.steps);
      if (!steps.length) throw new Error("추천 단계가 없습니다.");
      return { source: result.source === "ai" ? "ai" : "general", steps };
    } catch (error) {
      console.info("일반 프로세스 제안으로 전환합니다.", error.message);
      return { source: "general", steps: buildGeneralWorkflow(task) };
    } finally {
      clearTimeout(timeout);
    }
  }
};

function buildWorkflowTasks(parentTask, steps) {
  return normalizeWorkflowSteps(steps).filter((step) => step.included).map((step) => ({
    category: parentTask.category,
    title: step.title,
    dueDate: dateBefore(parentTask.dueDate, step.offset),
    priority: step.offset <= 3 ? "긴급" : "보통",
    memo: step.description || `${parentTask.title} 준비 단계 · D-${step.offset}`,
    autoGenerated: true,
    parentTaskId: parentTask.id,
    workflowTitle: parentTask.title,
    workflowOffset: step.offset
  }));
}

function renderWorkflowDraft() {
  const selectedCount = state.workflowDraft.filter((step) => step.included && step.title.trim()).length;
  elements.workflowSource.textContent = state.workflowSource === "ai" ? "AI 맞춤 제안" : "일반 프로세스 제안";
  elements.confirmWorkflow.textContent = `선택한 ${selectedCount}개 단계와 함께 등록`;
  elements.confirmWorkflow.disabled = state.saving;
  elements.workflowStepList.innerHTML = state.workflowDraft.map((step, index) => {
    const dueDate = state.pendingTask ? dateBefore(state.pendingTask.dueDate, step.offset) : "";
    return `
      <article data-workflow-step-id="${escapeHtml(step.id)}" class="rounded-2xl border p-4 transition ${step.included ? "border-slate-200 bg-white" : "border-slate-200 bg-slate-50 opacity-60"}">
        <div class="flex items-start gap-3">
          <label class="mt-1 flex shrink-0 cursor-pointer items-center gap-2 text-xs font-bold text-slate-600">
            <input type="checkbox" class="workflow-include h-5 w-5 rounded border-slate-300 text-blue-600 focus:ring-blue-500" ${step.included ? "checked" : ""} />
            <span class="sr-only">${index + 1}단계 포함</span>
          </label>
          <div class="min-w-0 flex-1">
            <div class="mb-2 flex items-center justify-between gap-2">
              <span class="text-[10px] font-black tracking-wider text-blue-600">준비 ${index + 1}단계</span>
              <span class="text-[11px] font-semibold text-slate-400">예정일 ${escapeHtml(dueDate)}</span>
            </div>
            <input type="text" maxlength="100" value="${escapeHtml(step.title)}" class="workflow-title min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold text-slate-800 outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50" aria-label="${index + 1}단계 제목" />
            <div class="mt-2 flex items-center gap-2">
              <label class="flex items-center gap-2 rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-600">D-<input type="number" min="0" max="365" value="${step.offset}" class="workflow-offset h-9 w-14 bg-transparent text-center text-sm font-black text-blue-700 outline-none" aria-label="${index + 1}단계 D-Day" /></label>
              <span class="text-[11px] font-medium text-slate-400">완료일 기준 며칠 전</span>
              <button type="button" class="delete-workflow-step ml-auto grid h-9 w-9 place-items-center rounded-lg text-slate-400 transition hover:bg-rose-50 hover:text-rose-600" aria-label="${index + 1}단계 삭제"><i class="fa-regular fa-trash-can" aria-hidden="true"></i></button>
            </div>
          </div>
        </div>
      </article>`;
  }).join("");
}

function escapeHtml(value = "") {
  return String(value).replace(/[&<>'"]/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;"
  })[character]);
}

function formatDisplayDate(value) {
  const date = parseLocalDate(value);
  if (Number.isNaN(date.getTime())) return "날짜 미정";
  return new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", weekday: "short" }).format(date);
}

function filteredTasks() {
  return state.tasks
    .filter((task) => {
      const days = getDaysUntil(task.dueDate);
      const keyword = state.query.trim().toLocaleLowerCase("ko");
      const matchesQuery = !keyword || `${task.title} ${task.memo} ${task.category} ${task.owner}`.toLocaleLowerCase("ko").includes(keyword);
      if (!matchesQuery) return false;
      if (state.filter === "pending") return !task.completed;
      if (state.filter === "urgent") return !task.completed && days <= 0;
      if (state.filter === "soon") return !task.completed && days >= 1 && days <= 3;
      if (state.filter === "done") return task.completed;
      if (CATEGORIES.includes(state.filter)) return task.category === state.filter;
      return true;
    })
    .sort((a, b) => {
      if (a.completed !== b.completed) return Number(a.completed) - Number(b.completed);
      return parseLocalDate(a.dueDate) - parseLocalDate(b.dueDate);
    });
}

function ddayClasses(tone) {
  return {
    overdue: "bg-red-100 text-red-700 ring-red-200",
    today: "deadline-pulse bg-red-600 text-white ring-red-300",
    soon: "bg-orange-100 text-orange-700 ring-orange-200",
    normal: "bg-slate-100 text-slate-600 ring-slate-200"
  }[tone];
}

function priorityClasses(priority) {
  return {
    긴급: "bg-red-50 text-red-700",
    보통: "bg-blue-50 text-blue-700",
    여유: "bg-emerald-50 text-emerald-700"
  }[priority] || "bg-slate-100 text-slate-600";
}

function categoryClasses(category) {
  return {
    "공문/보고": "border-blue-200 bg-blue-50 text-blue-700",
    "품의/정산": "border-emerald-200 bg-emerald-50 text-emerald-700",
    "학급/학생": "border-purple-200 bg-purple-50 text-purple-700",
    "행사/수업": "border-amber-200 bg-amber-50 text-amber-700",
    "연수/기타": "border-slate-200 bg-slate-50 text-slate-700"
  }[category] || "border-slate-200 bg-slate-50 text-slate-700";
}

function cardBorderClasses(task, tone) {
  if (task.completed) return "border-slate-200";
  if (tone === "overdue" || tone === "today") return "border-rose-300";
  if (tone === "soon") return "border-amber-300";
  return "border-slate-200";
}

function taskTemplate(task) {
  const dday = getDday(task);
  const badgeText = task.completed ? "완료" : dday.label;
  const badgeStyle = task.completed ? "bg-slate-100 text-slate-500 ring-slate-200" : ddayClasses(dday.tone);
  return `
    <article class="task-row rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${cardBorderClasses(task, dday.tone)} ${task.completed ? "task-complete" : ""}" data-task-id="${escapeHtml(task.id)}">
      <div class="flex items-center justify-between gap-3">
        <span class="flex flex-wrap items-center gap-2"><span class="rounded-lg border px-2.5 py-1 text-[11px] font-bold ${categoryClasses(task.category)}">📌 ${escapeHtml(task.category)}</span>${task.autoGenerated ? '<span class="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600">자동 일정</span>' : ""}</span>
        <span class="shrink-0 rounded-full px-3 py-1 text-[11px] font-black ring-1 ring-inset ${badgeStyle}">${escapeHtml(badgeText)}</span>
      </div>
      <div class="mt-4 flex items-start gap-3">
        <label class="relative mt-0.5 grid shrink-0 cursor-pointer place-items-center" aria-label="${escapeHtml(task.title)} 완료 상태">
          <input type="checkbox" class="task-checkbox peer h-6 w-6 cursor-pointer appearance-none rounded-lg border border-slate-300 bg-white transition checked:border-blue-500 checked:bg-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-100" ${task.completed ? "checked" : ""} />
          <svg class="pointer-events-none absolute hidden h-4 w-4 text-white peer-checked:block" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m4 10 4 4 8-8" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </label>
        <div class="min-w-0 flex-1">
          <div class="flex flex-wrap items-center gap-2"><h3 class="task-title break-words text-[15px] font-extrabold leading-snug text-slate-900">${escapeHtml(task.title)}</h3>${task.priority === "긴급" && !task.completed ? `<span class="rounded bg-rose-50 px-1.5 py-0.5 text-[10px] font-bold text-rose-600">긴급</span>` : ""}</div>
          ${task.memo ? `<p class="mt-2 text-xs leading-5 text-slate-500">${escapeHtml(task.memo)}</p>` : ""}
        </div>
      </div>
      <div class="mt-4 flex items-center justify-between gap-3 border-t border-slate-100 pt-3 text-xs font-medium text-slate-500">
        <span><i class="fa-regular fa-calendar mr-1.5 text-slate-400" aria-hidden="true"></i>마감: <strong class="font-semibold text-slate-600">${escapeHtml(task.dueDate)}</strong></span>
        <button type="button" class="delete-task rounded-lg p-1.5 text-slate-300 transition hover:bg-rose-50 hover:text-rose-500" aria-label="${escapeHtml(task.title)} 삭제"><i class="fa-regular fa-trash-can" aria-hidden="true"></i></button>
      </div>
    </article>`;
}

function renderWorkflowAlerts() {
  const alerts = state.tasks
    .filter((task) => task.autoGenerated && !task.completed)
    .sort((a, b) => parseLocalDate(a.dueDate) - parseLocalDate(b.dueDate))
    .slice(0, 3);

  elements.workflowAlertsSection.hidden = alerts.length === 0;
  elements.workflowAlertCount.textContent = `${alerts.length}개 단계`;
  elements.workflowAlertList.innerHTML = alerts.map((task, index) => {
    const days = getDaysUntil(task.dueDate);
    const timing = days < 0 ? "지금 처리 필요" : days === 0 ? "오늘 준비" : `${days}일 후 준비`;
    const tone = days <= 0 ? "border-rose-200 bg-rose-50 text-rose-700" : days <= 3 ? "border-amber-200 bg-amber-50 text-amber-700" : "border-blue-100 bg-white text-blue-700";
    return `
      <article class="rounded-xl border p-4 ${tone}">
        <div class="flex items-center justify-between gap-2">
          <span class="text-[10px] font-black tracking-wider">준비 ${index + 1}단계 · 마감 D-${escapeHtml(task.workflowOffset)}</span>
          <span class="rounded-full bg-white/70 px-2 py-0.5 text-[10px] font-bold">${escapeHtml(timing)}</span>
        </div>
        <h3 class="mt-2 text-sm font-extrabold leading-5 text-slate-900">${escapeHtml(task.title)}</h3>
        <p class="mt-1 truncate text-[11px] font-medium text-slate-500">${escapeHtml(task.workflowTitle)}</p>
        <p class="mt-3 text-[11px] font-bold"><i class="fa-regular fa-calendar mr-1" aria-hidden="true"></i>${escapeHtml(task.dueDate)}</p>
      </article>`;
  }).join("");
}

function renderStats() {
  const incomplete = state.tasks.filter((task) => !task.completed);
  const completedCount = state.tasks.length - incomplete.length;
  const completionRate = state.tasks.length ? Math.round((completedCount / state.tasks.length) * 100) : 0;
  elements.statUrgent.textContent = incomplete.filter((task) => getDaysUntil(task.dueDate) <= 0).length;
  elements.statSoon.textContent = incomplete.filter((task) => {
    const days = getDaysUntil(task.dueDate);
    return days >= 1 && days <= 3;
  }).length;
  elements.statProgress.textContent = incomplete.length;
  elements.statRate.textContent = `${completionRate}%`;
  elements.statCompleted.textContent = `${completedCount}/${state.tasks.length} 완료`;
  elements.statProgressBar.style.width = `${completionRate}%`;
  elements.filterAllCount.textContent = `(${state.tasks.length})`;
}

function renderFilters() {
  document.querySelectorAll(".filter-button").forEach((button) => {
    const active = button.dataset.filter === state.filter;
    button.className = `filter-button whitespace-nowrap rounded-xl px-3.5 py-1.5 transition ${active ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600 hover:bg-slate-100"}`;
    button.setAttribute("aria-pressed", String(active));
  });
}

function render() {
  renderStats();
  renderFilters();
  renderWorkflowAlerts();
  elements.loading.hidden = !state.loading;
  if (state.loading) {
    elements.taskList.innerHTML = "";
    elements.empty.hidden = true;
    return;
  }

  const tasks = filteredTasks();
  elements.resultCount.textContent = `검색 결과 ${tasks.length}건`;
  elements.taskList.innerHTML = tasks.map(taskTemplate).join("");
  elements.empty.hidden = tasks.length !== 0;
}

let toastTimer;
function showToast(message, isError = false) {
  clearTimeout(toastTimer);
  elements.toast.textContent = message;
  elements.toast.className = `fixed bottom-5 left-1/2 z-[60] -translate-x-1/2 rounded-xl px-4 py-3 text-sm font-bold text-white shadow-xl ${isError ? "bg-red-700" : "bg-slate-900"}`;
  elements.toast.hidden = false;
  toastTimer = setTimeout(() => { elements.toast.hidden = true; }, 2600);
}

function openModal() {
  elements.form.reset();
  elements.formError.hidden = true;
  elements.workflowReview.hidden = true;
  elements.workflowReviewContent.hidden = true;
  elements.workflowReviewLoading.hidden = false;
  elements.form.hidden = false;
  state.pendingTask = null;
  state.workflowDraft = [];
  elements.dueDateInput.value = formatLocalDate(startOfToday());
  elements.modal.hidden = false;
  document.body.classList.add("modal-open");
  requestAnimationFrame(() => elements.titleInput.focus());
}

function closeModal() {
  elements.modal.hidden = true;
  document.body.classList.remove("modal-open");
  state.pendingTask = null;
  state.workflowDraft = [];
  elements.openModal.focus();
}

async function handleToggle(checkbox) {
  const row = checkbox.closest("[data-task-id]");
  const task = state.tasks.find((item) => item.id === row.dataset.taskId);
  if (!task) return;

  const previous = task.completed;
  task.completed = checkbox.checked;
  render();
  try {
    const saved = await taskService.toggleTaskStatus(task.id, task.completed);
    task.completed = normalizeTask(saved).completed;
    render();
  } catch (error) {
    task.completed = previous;
    render();
    showToast(`상태 변경 실패: ${error.message}`, true);
  }
}

async function handleDelete(button) {
  const row = button.closest("[data-task-id]");
  const task = state.tasks.find((item) => item.id === row.dataset.taskId);
  if (!task || !window.confirm("이 업무를 삭제하시겠습니까?")) return;

  const previousTasks = [...state.tasks];
  state.tasks = state.tasks.filter((item) => item.id !== task.id);
  render();
  try {
    await taskService.deleteTask(task.id);
    showToast("업무를 삭제했습니다.");
  } catch (error) {
    state.tasks = previousTasks;
    render();
    showToast(`삭제 실패: ${error.message}`, true);
  }
}

async function handleSubmit(event) {
  event.preventDefault();
  if (state.saving || !elements.form.reportValidity()) return;
  state.saving = true;
  elements.submitTask.disabled = true;
  elements.submitTask.textContent = "준비 단계 생성 중...";
  elements.formError.hidden = true;

  state.pendingTask = Object.fromEntries(new FormData(elements.form).entries());
  elements.form.hidden = true;
  elements.workflowReview.hidden = false;
  elements.workflowReviewLoading.hidden = false;
  elements.workflowReviewContent.hidden = true;
  try {
    const suggestion = await workflowService.suggest(state.pendingTask);
    state.workflowDraft = suggestion.steps;
    state.workflowSource = suggestion.source;
    renderWorkflowDraft();
    elements.workflowReviewLoading.hidden = true;
    elements.workflowReviewContent.hidden = false;
  } catch (error) {
    state.workflowDraft = buildGeneralWorkflow(state.pendingTask);
    state.workflowSource = "general";
    renderWorkflowDraft();
    elements.workflowReviewLoading.hidden = true;
    elements.workflowReviewContent.hidden = false;
  } finally {
    state.saving = false;
    elements.submitTask.disabled = false;
    elements.confirmWorkflow.disabled = false;
    elements.submitTask.innerHTML = '<i class="fa-solid fa-wand-magic-sparkles mr-1" aria-hidden="true"></i>준비 단계 제안받기';
  }
}

function returnToTaskForm() {
  if (state.saving) return;
  elements.workflowReview.hidden = true;
  elements.form.hidden = false;
  requestAnimationFrame(() => elements.titleInput.focus());
}

async function confirmWorkflow() {
  if (state.saving || !state.pendingTask) return;
  const includedSteps = state.workflowDraft.filter((step) => step.included && step.title.trim());
  state.saving = true;
  elements.confirmWorkflow.disabled = true;
  elements.confirmWorkflow.textContent = "등록 중...";
  elements.workflowReviewError.hidden = true;

  try {
    const created = normalizeTask(await taskService.createTask(state.pendingTask));
    const workflowTasks = buildWorkflowTasks(created, includedSteps);
    const generatedTasks = [];
    let workflowError = null;
    for (const workflowTask of workflowTasks) {
      try {
        generatedTasks.push(normalizeTask(await taskService.createTask(workflowTask)));
      } catch (error) {
        workflowError = error;
        break;
      }
    }
    state.tasks.push(created, ...generatedTasks);
    closeModal();
    render();
    if (workflowError) {
      showToast(`업무는 등록했지만 준비 일정 일부를 만들지 못했습니다: ${workflowError.message}`, true);
    } else if (generatedTasks.length) {
      showToast(`새 업무와 준비 단계 ${generatedTasks.length}개를 등록했습니다.`);
    } else {
      showToast("새 업무를 등록했습니다.");
    }
  } catch (error) {
    elements.workflowReviewError.textContent = error.message || "업무 등록 중 오류가 발생했습니다.";
    elements.workflowReviewError.hidden = false;
  } finally {
    state.saving = false;
    elements.confirmWorkflow.disabled = false;
    if (!elements.modal.hidden) renderWorkflowDraft();
  }
}

function addWorkflowStep() {
  const suggestedOffset = Math.max(0, Math.min(365, Math.floor(Math.max(1, getDaysUntil(state.pendingTask.dueDate)) / 2)));
  const stepId = `step-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  state.workflowDraft.push({
    id: stepId,
    title: "새 준비 단계",
    offset: suggestedOffset,
    description: "",
    included: true
  });
  state.workflowDraft.sort((a, b) => b.offset - a.offset);
  renderWorkflowDraft();
  const addedTitle = elements.workflowStepList.querySelector(`[data-workflow-step-id="${stepId}"] .workflow-title`);
  if (addedTitle) addedTitle.select();
}

function getWorkflowDraftStep(target) {
  const row = target.closest("[data-workflow-step-id]");
  return row ? state.workflowDraft.find((step) => step.id === row.dataset.workflowStepId) : null;
}

function handleWorkflowStepInput(event) {
  const step = getWorkflowDraftStep(event.target);
  if (!step) return;
  if (event.target.matches(".workflow-title")) step.title = event.target.value;
  if (event.target.matches(".workflow-offset")) step.offset = Math.max(0, Math.min(365, Number(event.target.value) || 0));
}

function handleWorkflowStepChange(event) {
  const step = getWorkflowDraftStep(event.target);
  if (!step) return;
  if (event.target.matches(".workflow-include")) step.included = event.target.checked;
  if (event.target.matches(".workflow-offset")) state.workflowDraft.sort((a, b) => b.offset - a.offset);
  renderWorkflowDraft();
}

function handleWorkflowStepClick(event) {
  const button = event.target.closest(".delete-workflow-step");
  if (!button) return;
  const step = getWorkflowDraftStep(button);
  if (!step) return;
  state.workflowDraft = state.workflowDraft.filter((item) => item.id !== step.id);
  renderWorkflowDraft();
}

function bindEvents() {
  elements.filters.addEventListener("click", (event) => {
    const button = event.target.closest("[data-filter]");
    if (!button) return;
    state.filter = button.dataset.filter;
    render();
  });
  elements.search.addEventListener("input", (event) => {
    state.query = event.target.value;
    render();
  });
  document.querySelectorAll("[data-summary-filter]").forEach((button) => {
    button.addEventListener("click", () => {
      state.filter = button.dataset.summaryFilter;
      render();
    });
  });
  elements.taskList.addEventListener("change", (event) => {
    if (event.target.matches(".task-checkbox")) handleToggle(event.target);
  });
  elements.taskList.addEventListener("click", (event) => {
    const button = event.target.closest(".delete-task");
    if (button) handleDelete(button);
  });
  elements.openModal.addEventListener("click", openModal);
  elements.closeModal.addEventListener("click", closeModal);
  elements.cancelModal.addEventListener("click", closeModal);
  elements.backToTask.addEventListener("click", returnToTaskForm);
  elements.addWorkflowStep.addEventListener("click", addWorkflowStep);
  elements.confirmWorkflow.addEventListener("click", confirmWorkflow);
  elements.workflowStepList.addEventListener("input", handleWorkflowStepInput);
  elements.workflowStepList.addEventListener("change", handleWorkflowStepChange);
  elements.workflowStepList.addEventListener("click", handleWorkflowStepClick);
  elements.modal.addEventListener("click", (event) => {
    if (event.target === elements.modal) closeModal();
  });
  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && !elements.modal.hidden) closeModal();
  });
  elements.form.addEventListener("submit", handleSubmit);
}

async function init() {
  const gasEnvironment = isGasEnvironment();
  elements.userStatusPanel.hidden = !gasEnvironment;
  elements.userStatusText.textContent = gasEnvironment ? "Google Workspace 연결 중..." : "";
  elements.dueDateInput.min = formatLocalDate(startOfToday());
  bindEvents();
  render();
  try {
    const [tasks, userLabel] = await Promise.all([taskService.getTasks(), taskService.getCurrentUserEmail()]);
    state.tasks = Array.isArray(tasks) ? tasks.map(normalizeTask) : [];
    elements.userStatusText.textContent = gasEnvironment ? (userLabel || "Google Workspace 연결됨") : "";
  } catch (error) {
    state.tasks = isGasEnvironment() ? [] : loadLocalTasks();
    elements.userStatusText.textContent = "데이터 연결을 확인해 주세요";
    showToast(`업무를 불러오지 못했습니다: ${error.message}`, true);
  } finally {
    state.loading = false;
    render();
  }

  let renderedDate = formatLocalDate(startOfToday());
  window.setInterval(() => {
    const currentDate = formatLocalDate(startOfToday());
    if (currentDate !== renderedDate) {
      renderedDate = currentDate;
      render();
    }
  }, 60000);
}

init();
